// plugins/vuetify.ts
import { h, type Component } from 'vue'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import * as Lucide from '@lucide/vue'

const lucideComponents = Lucide as unknown as Record<string, Component>

const iconAliases: Record<string, string> = {
  '$cancel': 'X',
  '$checkboxIndeterminate': 'Minus',
  '$checkboxOff': 'Square',
  '$checkboxOn': 'SquareCheck',
  '$clear': 'CircleX',
  '$close': 'X',
  '$complete': 'Check',
  '$delete': 'Trash2',
  '$delimiter': 'Circle',
  '$dropdown': 'ChevronDown',
  '$edit': 'Pencil',
  '$error': 'CircleAlert',
  '$expand': 'ChevronDown',
  '$file': 'File',
  '$first': 'ChevronsLeft',
  '$info': 'Info',
  '$last': 'ChevronsRight',
  '$loading': 'LoaderCircle',
  '$menu': 'Menu',
  '$minus': 'Minus',
  '$next': 'ChevronRight',
  '$plus': 'Plus',
  '$prev': 'ChevronLeft',
  '$radioOff': 'Circle',
  '$radioOn': 'CircleDot',
  '$sortAsc': 'ArrowUp',
  '$sortDesc': 'ArrowDown',
  '$subgroup': 'ChevronDown',
  '$success': 'CircleCheck',
  '$unfold': 'ChevronsUpDown',
  '$warning': 'TriangleAlert',
  'mdi-account': 'User',
  'mdi-account-check-outline': 'UserCheck',
  'mdi-account-circle-outline': 'CircleUser',
  'mdi-account-edit-outline': 'UserPen',
  'mdi-account-group-outline': 'Users',
  'mdi-account-multiple': 'Users',
  'mdi-account-off-outline': 'UserX',
  'mdi-account-plus': 'UserPlus',
  'mdi-account-plus-outline': 'UserPlus',
  'mdi-account-search-outline': 'UserSearch',
  'mdi-alert': 'TriangleAlert',
  'mdi-alert-circle': 'CircleAlert',
  'mdi-alert-circle-outline': 'CircleAlert',
  'mdi-arrow-left': 'ArrowLeft',
  'mdi-arrow-right': 'ArrowRight',
  'mdi-bed': 'Bed',
  'mdi-bed-outline': 'Bed',
  'mdi-bell-service-outline': 'ConciergeBell',
  'mdi-bookmark': 'Bookmark',
  'mdi-bookmark-outline': 'Bookmark',
  'mdi-calendar': 'Calendar',
  'mdi-calendar-check': 'CalendarCheck',
  'mdi-calendar-check-outline': 'CalendarCheck',
  'mdi-calendar-clock': 'CalendarClock',
  'mdi-calendar-multiple': 'CalendarDays',
  'mdi-calendar-search': 'CalendarSearch',
  'mdi-cancel': 'CircleX',
  'mdi-car-outline': 'Car',
  'mdi-card-account-details-outline': 'IdCard',
  'mdi-cart': 'ShoppingCart',
  'mdi-cart-off': 'ShoppingCart',
  'mdi-cart-outline': 'ShoppingCart',
  'mdi-cash': 'Banknote',
  'mdi-cash-check': 'BadgeCheck',
  'mdi-cash-multiple': 'Coins',
  'mdi-cash-remove': 'BadgeX',
  'mdi-cash-sync': 'RefreshCw',
  'mdi-chart-bar': 'ChartColumn',
  'mdi-chart-line': 'ChartLine',
  'mdi-check': 'Check',
  'mdi-check-all': 'BadgeCheck',
  'mdi-check-circle': 'CircleCheck',
  'mdi-check-circle-outline': 'CircleCheck',
  'mdi-chevron-left': 'ChevronLeft',
  'mdi-chevron-right': 'ChevronRight',
  'mdi-close': 'X',
  'mdi-close-circle': 'CircleX',
  'mdi-close-circle-outline': 'CircleX',
  'mdi-cloud-off-outline': 'CloudOff',
  'mdi-cloud-upload': 'CloudUpload',
  'mdi-coffee': 'Coffee',
  'mdi-cog-outline': 'Settings',
  'mdi-content-save': 'Save',
  'mdi-currency-usd': 'BadgeDollarSign',
  'mdi-database-off-outline': 'DatabaseZap',
  'mdi-delete': 'Trash2',
  'mdi-domain': 'Building2',
  'mdi-door': 'DoorOpen',
  'mdi-door-closed': 'DoorClosed',
  'mdi-door-open': 'DoorOpen',
  'mdi-download': 'Download',
  'mdi-email-outline': 'Mail',
  'mdi-eye': 'Eye',
  'mdi-eye-off': 'EyeOff',
  'mdi-eye-outline': 'Eye',
  'mdi-file-document': 'FileText',
  'mdi-file-document-outline': 'FileText',
  'mdi-file-document-remove': 'FileX',
  'mdi-file-multiple-outline': 'Files',
  'mdi-folder-check': 'FolderCheck',
  'mdi-folder-open': 'FolderOpen',
  'mdi-folder-open-outline': 'FolderOpen',
  'mdi-format-list-bulleted': 'List',
  'mdi-fridge-outline': 'Refrigerator',
  'mdi-google': 'Chrome',
  'mdi-history': 'History',
  'mdi-home': 'House',
  'mdi-hotel': 'Hotel',
  'mdi-image-multiple': 'Images',
  'mdi-image-off': 'ImageOff',
  'mdi-image-plus': 'ImagePlus',
  'mdi-inbox-outline': 'Inbox',
  'mdi-information': 'Info',
  'mdi-information-outline': 'Info',
  'mdi-layers-outline': 'Layers',
  'mdi-lifebuoy': 'LifeBuoy',
  'mdi-loading': 'LoaderCircle',
  'mdi-lock': 'Lock',
  'mdi-lock-outline': 'Lock',
  'mdi-lock-reset': 'KeyRound',
  'mdi-login': 'LogIn',
  'mdi-logout': 'LogOut',
  'mdi-magnify': 'Search',
  'mdi-magnify-plus-outline': 'SearchPlus',
  'mdi-map-marker-path': 'MapPinned',
  'mdi-package-variant': 'Package',
  'mdi-package-variant-closed': 'PackageCheck',
  'mdi-pencil': 'Pencil',
  'mdi-pencil-outline': 'Pencil',
  'mdi-plus': 'Plus',
  'mdi-printer': 'Printer',
  'mdi-puzzle': 'Hotel',
  'mdi-receipt': 'Receipt',
  'mdi-refresh': 'RefreshCw',
  'mdi-room-service-outline': 'ConciergeBell',
  'mdi-run-fast': 'Activity',
  'mdi-shape-outline': 'Shapes',
  'mdi-shape-plus-outline': 'BadgePlus',
  'mdi-shield-account-outline': 'ShieldUser',
  'mdi-shield-admin': 'ShieldCheck',
  'mdi-shield-crown': 'Crown',
  'mdi-shopping-outline': 'ShoppingBag',
  'mdi-spa': 'Sparkles',
  'mdi-star-outline': 'Star',
  'mdi-state-machine': 'Workflow',
  'mdi-table': 'Table',
  'mdi-toolbox-outline': 'Wrench',
  'mdi-tools': 'Wrench',
  'mdi-trending-up': 'TrendingUp',
  'mdi-truck-fast': 'Truck',
  'mdi-view-dashboard-outline': 'LayoutDashboard',
  'mdi-washing-machine': 'WashingMachine',
  'mdi-weather-night': 'Moon',
}

const toPascalIconName = (icon: string) =>
  icon
    .replace(/^mdi-/, '')
    .replace(/-outline$/, '')
    .replace(/(^|-)([a-z0-9])/g, (_, __, char: string) => char.toUpperCase())

const resolveLucideIcon = (icon?: string | string[]) => {
  const iconName = Array.isArray(icon) ? icon[0] : icon
  if (!iconName) return lucideComponents.CircleHelp

  const mapped = iconAliases[iconName] || toPascalIconName(iconName)
  return lucideComponents[mapped] || lucideComponents.CircleHelp
}

const lucideSet = {
  component: (props: any) =>
    h(resolveLucideIcon(props.icon), {
      class: ['lucide-vuetify-icon', props.class],
      color: props.color,
      size: props.size || 20,
      strokeWidth: 2,
      absoluteStrokeWidth: true,
      'aria-hidden': props['aria-hidden'] ?? true,
    }),
}

export default defineNuxtPlugin((app) => {
  const vuetify = createVuetify({
    components,
    directives,
    icons: {
      defaultSet: 'lucide',
      sets: {
        lucide: lucideSet,
      },
    },
    theme: {
      defaultTheme: 'dark',
      themes: {
        dark: {
          dark: true,
          colors: {
            background: '#0B1117',
            surface: '#111827',
            'surface-bright': '#1F2937',
            'surface-variant': '#273449',
            primary: '#14B8A6',
            'primary-darken-1': '#0F766E',
            secondary: '#3B82F6',
            'secondary-darken-1': '#1D4ED8',
            accent: '#F59E0B',
            error: '#F87171',
            warning: '#FBBF24',
            info: '#60A5FA',
            success: '#34D399',
            'on-background': '#E2E8F0',
            'on-surface': '#CBD5E1',
          },
        },
        light: {
          dark: false,
          colors: {
            background: '#F1F5F9',
            surface: '#FFFFFF',
            'surface-bright': '#F8FAFC',
            'surface-variant': '#E2E8F0',
            primary: '#0F766E',
            'primary-darken-1': '#115E59',
            secondary: '#2563EB',
            'secondary-darken-1': '#1D4ED8',
            accent: '#D97706',
            error: '#DC2626',
            warning: '#D97706',
            info: '#2563EB',
            success: '#059669',
            'on-background': '#1E293B',
            'on-surface': '#334155',
          },
        },
      },
    },
    defaults: {
      VBtn: {
        variant: 'flat',
        rounded: 'md',
      },
      VCard: {
        rounded: 'lg',
        elevation: 0,
      },
      VTextField: {
        variant: 'outlined',
        density: 'comfortable',
        rounded: 'lg',
        color: 'primary',
      },
      VSelect: {
        variant: 'outlined',
        density: 'comfortable',
        rounded: 'lg',
        color: 'primary',
      },
      VChip: {
        rounded: 'md',
      },
    },
  })

  app.vueApp.use(vuetify)
})
