import { UserRole } from '~/types/auth'
import type { AreaPedidosConfig, CategoriaServicio } from '~/types/servicios'

export const AREA_PANEL_CONFIGS: Record<CategoriaServicio, AreaPedidosConfig> = {
  cafeteria: {
    categoria: 'cafeteria',
    titulo: 'Panel Cafetería',
    subtitulo: 'Resumen operativo del área y pedidos del día',
    iconoArea: 'mdi-coffee',
    colorArea: 'orange',
    labelMedio: 'En preparación',
    iconoMedio: 'mdi-coffee-maker',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Entregados hoy',
    iconoVacio: 'mdi-coffee-off',
    mensajeVacio: 'Sin pedidos activos en este momento',
    etiquetaItem: 'pedido',
    etiquetaItems: 'pedidos',
    accionAceptar: 'Preparar pedido',
    accionCompletar: 'Entregar',
  },
  lavanderia: {
    categoria: 'lavanderia',
    titulo: 'Panel Lavandería',
    subtitulo: 'Resumen operativo del área y lotes del día',
    iconoArea: 'mdi-washing-machine',
    colorArea: 'indigo',
    labelMedio: 'En proceso',
    iconoMedio: 'mdi-progress-clock',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Lotes cerrados',
    iconoVacio: 'mdi-washing-machine-alert',
    mensajeVacio: 'Sin lotes activos en este momento',
    etiquetaItem: 'lote',
    etiquetaItems: 'lotes',
    accionAceptar: 'Iniciar lavado',
    accionCompletar: 'Entregar lote',
  },
  spa: {
    categoria: 'spa',
    titulo: 'Panel Spa',
    subtitulo: 'Resumen operativo del área y servicios del día',
    iconoArea: 'mdi-spa',
    colorArea: 'pink',
    labelMedio: 'En curso',
    iconoMedio: 'mdi-progress-clock',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Servicios cerrados',
    iconoVacio: 'mdi-calendar-blank',
    mensajeVacio: 'Sin servicios activos en este momento',
    etiquetaItem: 'servicio',
    etiquetaItems: 'servicios',
    accionAceptar: 'Iniciar servicio',
    accionCompletar: 'Cerrar servicio',
  },
  room_service: {
    categoria: 'room_service',
    titulo: 'Panel Room Service',
    subtitulo: 'Resumen operativo del área y entregas del día',
    iconoArea: 'mdi-bell-service-outline',
    colorArea: 'teal',
    labelMedio: 'En ruta',
    iconoMedio: 'mdi-route',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Entregas cerradas',
    iconoVacio: 'mdi-bell-off',
    mensajeVacio: 'Sin entregas activas en este momento',
    etiquetaItem: 'entrega',
    etiquetaItems: 'entregas',
    accionAceptar: 'Preparar entrega',
    accionCompletar: 'Confirmar entrega',
  },
  minibar: {
    categoria: 'minibar',
    titulo: 'Panel Minibar',
    subtitulo: 'Resumen operativo del área y reposiciones del día',
    iconoArea: 'mdi-fridge-outline',
    colorArea: 'blue',
    labelMedio: 'En reponer',
    iconoMedio: 'mdi-package-variant',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Reposiciones cerradas',
    iconoVacio: 'mdi-fridge-off',
    mensajeVacio: 'Sin reposiciones activas en este momento',
    etiquetaItem: 'reposición',
    etiquetaItems: 'reposiciones',
    accionAceptar: 'Iniciar reposición',
    accionCompletar: 'Cerrar reposición',
  },
  transporte: {
    categoria: 'transporte',
    titulo: 'Panel Transporte',
    subtitulo: 'Resumen operativo del área y traslados del día',
    iconoArea: 'mdi-car-outline',
    colorArea: 'cyan',
    labelMedio: 'En ruta',
    iconoMedio: 'mdi-map-marker-path',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Traslados cerrados',
    iconoVacio: 'mdi-car-off',
    mensajeVacio: 'Sin traslados activos en este momento',
    etiquetaItem: 'traslado',
    etiquetaItems: 'traslados',
    accionAceptar: 'Iniciar traslado',
    accionCompletar: 'Cerrar traslado',
  },
  tours: {
    categoria: 'tours',
    titulo: 'Panel Tours',
    subtitulo: 'Resumen operativo del área y excursiones del día',
    iconoArea: 'mdi-map-marker-path',
    colorArea: 'lime',
    labelMedio: 'En curso',
    iconoMedio: 'mdi-walk',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Tours cerrados',
    iconoVacio: 'mdi-map-marker-off',
    mensajeVacio: 'Sin tours activos en este momento',
    etiquetaItem: 'tour',
    etiquetaItems: 'tours',
    accionAceptar: 'Iniciar tour',
    accionCompletar: 'Cerrar tour',
  },
  eventos: {
    categoria: 'eventos',
    titulo: 'Panel Eventos',
    subtitulo: 'Resumen operativo del área y eventos del día',
    iconoArea: 'mdi-party-popper',
    colorArea: 'deep-purple',
    labelMedio: 'En preparación',
    iconoMedio: 'mdi-calendar-clock',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Eventos cerrados',
    iconoVacio: 'mdi-calendar-remove',
    mensajeVacio: 'Sin eventos activos en este momento',
    etiquetaItem: 'evento',
    etiquetaItems: 'eventos',
    accionAceptar: 'Iniciar evento',
    accionCompletar: 'Cerrar evento',
  },
  mantenimiento: {
    categoria: 'mantenimiento',
    titulo: 'Panel Mantenimiento',
    subtitulo: 'Resumen operativo del área y tareas del día',
    iconoArea: 'mdi-toolbox-outline',
    colorArea: 'brown',
    labelMedio: 'En proceso',
    iconoMedio: 'mdi-tools',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Tareas cerradas',
    iconoVacio: 'mdi-hammer-screwdriver',
    mensajeVacio: 'Sin tareas activas en este momento',
    etiquetaItem: 'tarea',
    etiquetaItems: 'tareas',
    accionAceptar: 'Iniciar tarea',
    accionCompletar: 'Cerrar tarea',
  },
  otros: {
    categoria: 'otros',
    titulo: 'Panel Otros',
    subtitulo: 'Resumen operativo del área',
    iconoArea: 'mdi-dots-horizontal-circle-outline',
    colorArea: 'grey',
    labelMedio: 'En proceso',
    iconoMedio: 'mdi-progress-clock',
    estadoMedio: 'en_preparacion',
    estadoCompletado: 'entregado',
    labelCompleto: 'Cerrados hoy',
    iconoVacio: 'mdi-inbox-outline',
    mensajeVacio: 'Sin solicitudes activas en este momento',
    etiquetaItem: 'solicitud',
    etiquetaItems: 'solicitudes',
    accionAceptar: 'Procesar',
    accionCompletar: 'Cerrar',
  },
}

export const getAreaConfigByRole = (role: UserRole | null | undefined): AreaPedidosConfig => {
  if (!role) {
    return AREA_PANEL_CONFIGS.cafeteria
  }

  const key = role as CategoriaServicio
  if (key in AREA_PANEL_CONFIGS) {
    return AREA_PANEL_CONFIGS[key]
  }

  return AREA_PANEL_CONFIGS.cafeteria
}

export const getAreaConfigByCategoria = (categoria: keyof typeof AREA_PANEL_CONFIGS): AreaPedidosConfig => {
  return AREA_PANEL_CONFIGS[categoria] || AREA_PANEL_CONFIGS.cafeteria
}
